# Generated by Django 4.2.4 on 2023-08-12 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.PositiveIntegerField()),
                ('prefijo_cuil', models.PositiveIntegerField()),
                ('sufijo_cuil', models.PositiveIntegerField()),
                ('cod_area', models.IntegerField()),
                ('telefono', models.CharField(max_length=150)),
                ('domicilio', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro/Prefiero no decirlo')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('editar_cv', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
