# Generated by Django 4.2.4 on 2023-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs_app', '0002_alter_profile_cod_area_alter_profile_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
