# Generated by Django 4.2.4 on 2023-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs_app', '0003_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
