# Generated by Django 4.2.4 on 2023-08-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs_app', '0005_remove_profile_fecha_nacimiento_profile_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefijo_cuil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sufijo_cuil',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
