# Generated by Django 4.2.4 on 2023-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs_app', '0006_alter_profile_dni_alter_profile_prefijo_cuil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cantidad_hijos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='imprime_cantidad_hijos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='imprime_estado_civil',
            field=models.BooleanField(default=True),
        ),
    ]
