# Generated by Django 4.2.4 on 2023-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs_app', '0007_profile_cantidad_hijos_profile_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cantidad_hijos',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
