# Generated by Django 4.2.4 on 2023-08-17 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvs_app', '0011_academic_data_year_fin_academic_data_year_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='academic_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=80, null=True)),
                ('puesto', models.CharField(blank=True, max_length=80, null=True)),
                ('month_inicio', models.CharField(blank=True, max_length=2, null=True)),
                ('year_inicio', models.CharField(blank=True, max_length=4, null=True)),
                ('month_fin', models.CharField(blank=True, max_length=2, null=True)),
                ('year_fin', models.CharField(blank=True, max_length=4, null=True)),
                ('referencia_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('referencia_puesto', models.CharField(blank=True, max_length=30, null=True)),
                ('referencia_cod_area', models.CharField(blank=True, max_length=5, null=True)),
                ('referencia_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
