# Generated by Django 4.2.4 on 2023-08-20 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvs_app', '0013_alter_job_empresa_alter_job_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(blank=True, max_length=300, null=True)),
                ('objetivo_imp', models.BooleanField(default=True)),
                ('aptitudes', models.CharField(blank=True, max_length=300, null=True)),
                ('aptitudes_imp', models.BooleanField(default=True)),
                ('habilidades', models.CharField(blank=True, max_length=300, null=True)),
                ('habilidades_imp', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
